### ISSUE TITLE
Some bash scripts do not have executable permissions

### ISSUE THREAD

**Issue by saadismail** [LandRover/StaffjoyV2#12]
We use Github to track bugs in Staffjoy. Please answer these questions before submitting your issue. All of our code is in one place, so please preface the title with the system where the bug is (e.g. "company api" or "www"). Thanks!

### What environment did you encounter the issue in?

development

### Which browser are you using?

N/A

### What did you do?

`vagrant up`

### What did you expect to see?

VM to get up with all services.

### What did you see instead?

```
default: + sudo /bin/bash /home/vagrant/golang/src/v2.staffjoy.com/vagrant/ubuntu_mirror_replace_to_fastest.sh
default: /home/vagrant/golang/src/v2.staffjoy.com/vagrant/ubuntu_mirror_replace_to_fastest.sh: line 15: ./helpers/ubuntu_mirror_test.sh: Permission denied
default: Invalid mirror_url found:
default: Usage: sudo /home/vagrant/golang/src/v2.staffjoy.com/vagrant/ubuntu_mirror_replace_to_fastest.sh [mirror_url]
default: Example: sudo /home/vagrant/golang/src/v2.staffjoy.com/vagrant/ubuntu_mirror_replace_to_fastest.sh http://archive.ubuntu.com/ubuntu
default: Replaces the apt mirror to the input mirror_url
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

Appearently there are some shell scripts which were missed as a part of [3fd94ce0d0edc1a6c0d25b1a5c76ad5f09bd8252](https://github.com/LandRover/StaffjoyV2/commit/3fd94ce0d0edc1a6c0d25b1a5c76ad5f09bd8252)

Would it be fine if I create a PR making all the shell scripts executable?

**Comment by LandRover** [comment]
Hey,
I've fixed it due to another ticket, you can take master it should be ok.

Please update here whether it went smooth,  I really want the feedback.

Thanks,
Oleg.

**Comment by LandRover** [comment]
Tested on a clean Mac install, works correctly.
