### ISSUE TITLE
Provide container images

### ISSUE THREAD

**Issue by adberger** [LandRover/StaffjoyV2#13]
The dev setup doesn't work for me on a windows machine.
Is it possible to provide built container images over DockerHub or something?
So we could get a working prototype faster than with the current instructions?

**Comment by LandRover** [comment]
Did you follow the steps installing Vagrant and Virtualbox?

I've just performed a clean setup via 'vagrant up'

Could you please share more information where did it stuck?

**Comment by adberger** [comment]
No longer relevant, thanks anyway!
