### ISSUE TITLE
Error when building Unison.

### ISSUE THREAD

**Issue by AntSwift** [LandRover/StaffjoyV2#9]
Hi, can I ask what version of macOS you are using to develop this repo further? I'm having some issues building Unison from source using the instructions provided in the readme.

### What environment did you encounter the issue in?

development - macOS Catalina - 10.15.5

### What did you do?

Attempting to compile and install Unison.

### What did you expect to see?

Successful compilation.

### What did you see instead?

An error during linking.

### Are there any logs indicating an issue?

```
ld: Assertion failed: (targetAtom != NULL), function Fixup, file /Library/Caches/com.apple.xbs/Sources/ld64/ld64-556.6/src/ld/ld.hpp, line 785.
clang: error: linker command failed with exit code 1 (use -v to see invocation)
File "caml_startup", line 1:
Error: Error during linking
make: *** [unison] Error 2
```

**Comment by Juanvulcano** [comment]
I am having the following error as well :) 

```
A linker snapshot was created at:
	/tmp/unison-2020-06-30-133122.ld-snapshot
ld: Assertion failed: (targetAtom != NULL), function Fixup, file /Library/Caches/com.apple.xbs/Sources/ld64/ld64-530/src/ld/ld.hpp, line 780.
clang: error: linker command failed with exit code 1 (use -v to see invocation)
File "caml_startup", line 1:
Error: Error during linking
make: *** [unison] Error 2
```

**Comment by LandRover** [comment]
I've removed Unison completely, don't see any value works perfectly fine on Catalina without.

Not needed overhead.
